#! /bin/bash
#
# usage: allPairsTimeScript algorithm
#
# Run timing tests with a specified algorithm.
# The algorithm argument may be edmondsKarp or floyd
#
algo="edmondsKarp"
if [ $# -eq 1 ] ; then
	algo=$1
fi;

echo "density 3 graphs"
echo "algorithm n m lo hi avg min max"
k=6;
while [ $k -le 12 ] ; do
	n=$((2**k)); m=$((3*n/2))
	timeAllPairs $algo 20 $n $m 1 $m  
	k=$((k+1))
done

echo "density lg(n) graphs"
echo "algorithm n m lo hi avg min max"
k=6; 
while [ $k -le 12 ] ; do
	n=$((2**k)); m=$((k*n))
	timeAllPairs $algo 20 $n $m 1 $m  
	k=$((k+1))
done
