#! /bin/bash
#
# usage: evalScript algorithm [k]
#
# Run evaluation tests.
#

k=2
for meth in "cover" "layers0" "layers1" "layers2" "layers3" "greedy1" "greedy2" "greedy3"; do
	n1=100
	n2=${n1}
	maxn2=$((16*n1))
	while [ ${n2} -le ${maxn2} ] ; do
		d2=$((n1/2))
		d1=$((n2*d2/n1))

		i=1
		cb=${d2}
		while [ $i -le 32 ] ; do
			g1=${d2}
			cb=$((d2+i))
			evalGcolor 10 ${n1} ${n2} ${d1} ${g1} ${cb} ${meth} $k
			i=$((2*i))
		done
		n2=$((2*n2))
	done
done
