#! /bin/bash
#
# usage: testScript 
#
# Run unit tests on various algorithms, comparing results for
# different algorithms.
#
echo "unweighted bipartite graphs"
for seed in 1 2 3 4 5 6 7 8 9 10 ; do
	echo -n "flowMatch "
	randGraph bigraph 1000 2000 ${seed} 1 | testMatch flowMatch
	echo -n "hopcroftKarp "
	randGraph bigraph 1000 2000 ${seed} 1 | testMatch hopcroftKarp
	echo -n "edmondsGabow "
	randGraph bigraph 1000 2000 ${seed} 1 | testMatch edmondsGabow
	echo -n "fastEdmondsGabow "
	randGraph bigraph 1000 2000 ${seed} 1 | testMatch fastEdmondsGabow
	echo " "
done
echo "weighted bipartite graphs"
for seed in 1 2 3 4 5 6 7 8 9 10 ; do
	echo -n "flowMatchWt "
	randGraph wbigraph 1000 2000 1 10000 ${seed} 1 | testMatch flowMatchWt
	echo -n "hungarian "
	randGraph wbigraph 1000 2000 1 10000 ${seed} 1 | testMatch hungarian
	echo -n "edmondsGMGbi "
	randGraph wbigraph 1000 2000 1 10000 ${seed} 1 | testMatch edmondsGMGbi
	echo " "
done
echo "unweighted general graphs"
for seed in 1 2 3 4 5 6 7 8 9 10 ; do
	echo -n "edmondsGabow "
	randGraph ugraph 1000 2000 ${seed} 1 | testMatch edmondsGabow
	echo -n "fastEdmondsGabow "
	randGraph ugraph 1000 2000 ${seed} 1 | testMatch fastEdmondsGabow
	echo " "
done
