#! /bin/bash
#
# usage: ubScript algorithm
#
# Run unit test on series of random unweighted bipartite graphs,
# with a specified algorithm.
#
# The algorithm argument is one of hopcroftKarp, edmondsGabow,
# fastEdmondsGabow, maxdMatch, fastMaxdMatch
#
algo="hopcroftKarp"
if [ $# -eq 1 ] ; then
	algo=$1
fi;
echo "testing algorithm: " $algo

echo ""; echo "testing 20 vertex regular bipartite graph"
randGraph biregular 10 3 1 1 | testMatch $algo show verify

echo ""; echo "testing 40 vertex bipartite graph"
randGraph bigraph 20 8 2 1 | testMatch $algo show verify

echo ""; echo "testing 20 vertex tree"
randGraph tree 20 3 1 | testMatch $algo show verify

echo ""; echo "testing 20 vertex non-bipartite graph"
randGraph ugraph 20 50 4 1 | testMatch $algo show verify

echo ""; echo "testing 10000 vertex bipartite graphs"
for seed in 5 6 7 8 9 10 11 12 13 14; do
	randGraph bigraph 5000 8000 $seed 1 | testMatch $algo verify
done
