#! /bin/bash
#
# usage: uTimeScript algorithm 
#
# Run timing tests with a specified algorithm.
# The algorithm argument is one of match_eg, match_egf
#
algo="match_eg"
if [ $# -eq 1 ] ; then
        algo=$1
fi;

echo "degree 3 graphs"
echo "algorithm n m avg min max"
k=6;
while [ $k -le 12 ] ; do
        n=$((2**k)); m=$((3*n))
        timeMatch $algo 20 $n $m 
        k=$((k+1))
done

echo "degree lg(n) graphs"
echo "algorithm n m avg min max"
k=6; 
while [ $k -le 12 ] ; do
        n=$((2**k)); m=$((k*n))
        timeMatch $algo 20 $n $m
        k=$((k+1))
done
