#! /bin/bash
#
# usage: bfsScript n m seed
#
#
n=10
if [ $# -ge 1 ] ; then
	n=$1
fi;
m=15
if [ $# -ge 2 ] ; then
	m=$2
fi;
seed=1
if [ $# -ge 3 ] ; then
	seed=$3
fi;

randGraph ugraph $n $m $seed 0 | testBfs
